(()=>{"use strict";
const app=document.getElementById("app");
const S={token:localStorage.getItem("rd_token"),role:localStorage.getItem("rd_role"),view:"dashboard",detail:null,cache:{}};
const adminPath=()=>location.pathname.startsWith("/admin");
const roles={manager:["OWNER","ADMIN"],operator:["OWNER","ADMIN","ANALYST"],read:["OWNER","ADMIN","ANALYST","CLIENT","VIEWER"]};
const can=(kind)=>roles[kind].includes(S.role);
const esc=x=>String(x??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const arr=x=>Array.isArray(x)?x:(x?.items||x?.data||x?.results||[]);
const fmt=x=>{if(!x)return "—";const d=new Date(x);return Number.isNaN(d.getTime())?String(x):d.toLocaleString("fr-FR")};
const field=(k,v)=>'<div class="detail-field"><small>'+esc(k)+'</small><div>'+esc(v)+'</div></div>';
const button=(label,action,cls="btn")=>'<button class="'+cls+'" data-action="'+esc(action)+'">'+esc(label)+'</button>';
async function api(url,opts={}){const h={"Content-Type":"application/json",...(opts.headers||{})};if(S.token)h.Authorization="Bearer "+S.token;const r=await fetch(url,{...opts,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error?.message||d?.error?.code||"Erreur HTTP "+r.status);return d}
const post=(url,body={})=>api(url,{method:"POST",body:JSON.stringify(body)});
function login(){app.innerHTML='<main class="login"><section class="loginbox"><div><b style="color:#0878ee">◆</b> Review Defense</div><h1>Votre espace</h1><p>Connectez-vous pour suivre vos avis, dossiers, preuves et actions.</p><form id="login-form"><div class="field"><label>Organisation ID</label><input name="organization_id" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Mot de passe</label><input name="password" type="password" required></div><div class="field"><label>Code MFA si demandé</label><input name="mfa_code" inputmode="numeric"></div><div class="err" id="login-error"></div><button class="btn primary" style="width:100%;text-align:center" type="submit">Se connecter</button></form></section></main>';
document.getElementById("login-form").onsubmit=async e=>{e.preventDefault();const err=document.getElementById("login-error");err.textContent="";try{const d=await post("/v1/auth/login",Object.fromEntries(new FormData(e.currentTarget)));S.token=d.access_token;S.role=d.role;localStorage.setItem("rd_token",S.token);localStorage.setItem("rd_role",S.role);start()}catch(x){err.textContent=x.message}}}
const client=[["dashboard","Vue d’ensemble"],["reviews","Avis"],["cases","Dossiers"],["evidence","Preuves"],["billing","Abonnement"]];
const admin=[["queue","File de traitement"],["escalations","Escalades SLA"],["approvals","Approbations"],["team","Équipe"],["notifications","Notifications"],["submissions","Soumissions"]];
const allLabels=Object.fromEntries([...client,...admin]);
function shell(){let items=[...client];if(can("operator"))items.push(...admin.filter(x=>["queue","escalations"].includes(x[0])));if(can("manager"))items.push(...admin.filter(x=>["approvals","team","notifications","submissions"].includes(x[0])));
app.innerHTML='<div class="shell"><aside class="side"><a class="brand" href="/"><b>◆</b> Review Defense</a><nav>'+items.map(x=>'<button data-view="'+x[0]+'">'+x[1]+'</button>').join("")+'</nav><div class="role">Accès<br><strong>'+esc(S.role)+'</strong></div></aside><main class="main"><header class="top"><div class="top-left"><button class="btn menu" id="menu">☰</button><div><h1 id="page-title">Vue d’ensemble</h1><p>Votre activité au même endroit.</p></div></div><div class="actions"><button class="btn" id="refresh">Actualiser</button><button class="btn" id="logout">Déconnexion</button></div></header><section class="content">'+items.map(x=>'<div class="view" id="view-'+x[0]+'"></div>').join("")+'</section></main></div><div id="modal-root"></div>';
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{S.view=b.dataset.view;document.querySelector(".side").classList.remove("open");show()});
document.getElementById("logout").onclick=async()=>{try{await post("/v1/logout")}catch{}localStorage.removeItem("rd_token");localStorage.removeItem("rd_role");S.token=null;login()};
document.getElementById("refresh").onclick=()=>load(S.view);
document.getElementById("menu").onclick=()=>document.querySelector(".side").classList.toggle("open");
document.getElementById("modal-root").addEventListener("click",onAction);
show()}
function show(){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.getElementById("view-"+S.view)?.classList.add("active");document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===S.view));document.getElementById("page-title").textContent=allLabels[S.view]||"Espace";load(S.view)}
function table(items,cols,kind){const rows=items.map(x=>'<tr class="row-click" data-open="'+kind+'" data-id="'+esc(x.review_id||x.case_id||x.evidence_id||x.notification_id||x.approval_id||x.member_id||x.id||"")+'">'+cols.map(c=>'<td>'+ (c.render?c.render(x):esc(x[c.key]))+'</td>').join("")+'</tr>').join("");return '<div class="table"><table><thead><tr>'+cols.map(c=>'<th>'+c.label+'</th>').join("")+'</tr></thead><tbody>'+(rows||'<tr><td colspan="'+cols.length+'" class="empty">Aucune donnée à afficher.</td></tr>')+'</tbody></table></div>'}
function panel(title,body,actions=""){return '<section class="card panel"><div class="panel-head"><div><h2>'+title+'</h2></div><div class="actions">'+actions+'</div></div>'+body+'</section>'}
function bindList(el,items,cols,kind){el.innerHTML=panel(allLabels[S.view],'<input class="search" id="list-search" placeholder="Rechercher…">'+table(items,cols,kind),'<span>'+items.length+' élément(s)</span>');const input=el.querySelector("#list-search");input.oninput=()=>{const q=input.value.toLowerCase();el.querySelectorAll("tbody tr").forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))};el.querySelectorAll("[data-open]").forEach(r=>r.onclick=()=>openDetail(r.dataset.open,r.dataset.id))}

function renderTeam(el,items){
 const body='<p>Gérez les membres et leurs droits d’accès. Les changements de rôle sont appliqués côté serveur.</p>'+table(items,[{label:"Membre",render:x=>esc(x.email||x.user_id)},{label:"Rôle",render:x=>esc(x.role)},{label:"Identifiant",render:x=>esc(x.user_id)}],"team");
 el.innerHTML=panel("Équipe",body,button("Inviter un membre","invite-member","btn primary"));
 el.querySelectorAll("[data-open]").forEach(r=>r.onclick=()=>openDetail("team",r.dataset.id));
}
function renderEscalations(el,items){
 const body='<p>Suivi des alertes d’échéance. La prise en compte et la résolution sont enregistrées côté serveur.</p>'+table(items,[{label:"Dossier",render:x=>esc(x.case_id)},{label:"Niveau",render:x=>esc(x.level)},{label:"État",render:x=>esc(x.status)},{label:"Assigné",render:x=>esc(x.assigned_to||"—")},{label:"Temps restant",render:x=>esc(x.sla?.remaining_seconds!=null?Math.round(x.sla.remaining_seconds/60)+" min":"—")}],"escalations");
 el.innerHTML=panel("Escalades SLA",body);
 el.querySelectorAll("[data-open]").forEach(r=>r.onclick=()=>openDetail("escalations",r.dataset.id));
}

async function load(v){const el=document.getElementById("view-"+v);if(!el)return;el.innerHTML='<div class="card">Chargement…</div>';try{
if(v==="dashboard")return await dashboard(el);
if(v==="billing")return await billing(el);
const urls={reviews:"/v1/reviews",cases:"/v1/cases",evidence:"/v1/evidence",queue:"/v1/review-queue",escalations:"/v1/escalations",approvals:"/v1/approvals",team:"/v1/organization/members",notifications:"/v1/notifications",submissions:"/v1/submissions"};
const data=arr(await api(urls[v]));S.cache[v]=data;
const cols={
reviews:[{label:"Avis",render:x=>esc(x.author_display_name||x.review_id)},{label:"Note",render:x=>esc(x.rating)+"/5"},{label:"Date",render:x=>esc(fmt(x.published_at))}],
cases:[{label:"Dossier",render:x=>esc(x.case_id)},{label:"Avis associé",render:x=>esc(x.review_id)},{label:"Statut",render:x=>'<span class="pill">'+esc(x.status)+'</span>'},{label:"Créé le",render:x=>esc(fmt(x.created_at))}],
evidence:[{label:"Fichier",render:x=>esc(x.filename)},{label:"Dossier",render:x=>esc(x.case_id)},{label:"Intégrité",render:x=>'<span class="pill">'+esc(x.status|| (x.verified?"VERIFIED":"PENDING"))+'</span>'}],
queue:[{label:"Dossier",render:x=>esc(x.case_id)},{label:"Priorité",render:x=>esc(x.priority)},{label:"Score",render:x=>esc(x.priority_score)},{label:"Assigné",render:x=>esc(x.assigned_to||"Non assigné")},{label:"SLA",render:x=>esc(x.sla?.status||"—")}],
escalations:[{label:"Dossier",render:x=>esc(x.case_id)},{label:"Niveau",render:x=>esc(x.level)},{label:"État",render:x=>esc(x.status)},{label:"Assigné",render:x=>esc(x.assigned_to||"Non assigné")},{label:"Échéance",render:x=>esc(fmt(x.due_at||x.created_at))}],
approvals:[{label:"Approbation",render:x=>esc(x.approval_id||x.decision_id)},{label:"Dossier",render:x=>esc(x.case_id)},{label:"Statut",render:x=>esc(x.status||x.state)}],
team:[{label:"Membre",render:x=>esc(x.email||x.name||x.user_id)},{label:"Rôle",render:x=>esc(x.role)},{label:"Statut",render:x=>esc(x.status||"Actif")}],
notifications:[{label:"Notification",render:x=>esc(x.subject||x.notification_id)},{label:"Canal",render:x=>esc(x.channel)},{label:"Statut",render:x=>esc(x.status)},{label:"Créée le",render:x=>esc(fmt(x.created_at))}],
submissions:[{label:"Soumission",render:x=>esc(x.submission_id||x.case_id)},{label:"Dossier",render:x=>esc(x.case_id)},{label:"Statut",render:x=>esc(x.status)}]
};
if(v==="team")return renderTeam(el,data);if(v==="escalations")return renderEscalations(el,data);bindList(el,data,cols[v]||[{label:"Élément",key:"id"}],v);
}catch(e){el.innerHTML=panel(allLabels[v]||v,'<div class="notice">'+esc(e.message)+'</div>')}}
async function dashboard(el){const jobs=[api("/v1/reviews"),api("/v1/cases")];if(can("operator"))jobs.push(api("/v1/notifications").catch(()=>({items:[]})));if(can("manager"))jobs.push(api("/v1/approvals").catch(()=>({items:[]})));const rs=await Promise.allSettled(jobs);const counts=rs.map(x=>x.status==="fulfilled"?arr(x.value).length:null);const names=["Avis suivis","Dossiers actifs","Notifications","Actions à valider"];el.innerHTML='<div class="cards">'+counts.map((n,i)=>'<div class="card k"><small>'+names[i]+'</small><strong>'+(n??"—")+'</strong><span>dans votre espace</span></div>').join("")+'</div>'+panel("Parcours Review Defense",'<div class="steps"><span><b>01</b> Analyse</span><span><b>02</b> Dossier</span><span><b>03</b> Preuves</span><span><b>04</b> Validation humaine</span><span><b>05</b> Suivi</span></div><p>Ouvrez un avis ou un dossier pour consulter les informations détaillées et les actions autorisées selon votre rôle.</p>')+panel("Accès rapide",'<div class="service-strip"><div><b>Suivre les avis</b><span>Lire le contenu et les signaux détectés.</span></div><div><b>Constituer un dossier</b><span>Centraliser les pièces et leur vérification.</span></div><div><b>Suivre les décisions</b><span>Consulter l’historique et les validations.</span></div></div>')}
async function billing(el){const items=arr(await api("/v1/billing/catalog"));el.innerHTML=panel("Catalogue des offres",'<p>Les informations tarifaires sont chargées depuis le backend.</p>'+table(items,[{label:"Offre",render:x=>esc(x.name_fr||x.offer_id)},{label:"Type",render:x=>esc(x.kind)},{label:"Prix",render:x=>esc(x.amount!=null?x.amount+" "+(x.currency||"EUR"):"Sur devis")}],"billing"))}
async function openDetail(kind,id){if(!id)return;const root=document.getElementById("modal-root");root.innerHTML='<div class="overlay"><section class="card drawer">Chargement de la fiche…</section></div>';try{let data={},title=kind; if(kind==="reviews"){data=await api("/v1/reviews/"+encodeURIComponent(id));title="Fiche avis"}
if(kind==="cases"){const base="/v1/cases/"+encodeURIComponent(id);const results=await Promise.allSettled([api(base),api(base+"/workspace"),api(base+"/history"),api(base+"/sla"),api(base+"/review-checklist"),api(base+"/evidence-matrix"),api(base+"/contradictions")]);data={};["detail","workspace","history","sla","checklist","matrix","contradictions"].forEach((k,i)=>{if(results[i].status==="fulfilled")data[k]=results[i].value;else data[k+"_error"]=results[i].reason.message});title="Dossier "+id}
if(kind==="evidence"){data=await api("/v1/evidence/"+encodeURIComponent(id));title="Preuve"}
if(kind==="queue"){const q=(S.cache.queue||[]).find(x=>x.case_id===id);data={queue:q};title="File de traitement"}
if(kind==="approvals"){data=(S.cache.approvals||[]).find(x=>(x.approval_id||x.decision_id)===id)||{};title="Approbation"}
if(kind==="notifications"){data=(S.cache.notifications||[]).find(x=>(x.notification_id||x.id)===id)||{};title="Notification"}
if(kind==="team"){data=(S.cache.team||[]).find(x=>(x.member_id||x.user_id)===id)||{};title="Membre"}
renderDetail(root,kind,id,title,data)
}catch(e){root.innerHTML='<div class="overlay"><section class="card drawer"><button class="btn close" data-action="close">×</button><div class="notice">'+esc(e.message)+'</div></section></div>'}}
function jsonBlock(x){return '<pre style="white-space:pre-wrap;overflow-wrap:anywhere;background:#f7f9fb;padding:12px;border-radius:10px;font-size:10px">'+esc(JSON.stringify(x,null,2))+'</pre>'}
function factsMarkup(rows,evidenceRows,caseId){if(!rows.length)return '<p class="muted">Aucun fait extrait pour le moment.</p>';return '<div class="table"><table><thead><tr><th>Fait</th><th>Valeur proposée</th><th>Source</th><th>État</th><th></th></tr></thead><tbody>'+rows.map(x=>{const evidence=(evidenceRows||[]).find(e=>e.evidence_id===x.evidence_id);return '<tr><td>'+esc(x.key)+'</td><td>'+esc(x.value)+'</td><td>'+esc(x.source_location||x.evidence_id)+'</td><td>'+(x.verified?'<span class="pill">Vérifié</span>':'<span class="pill">À vérifier</span>')+'</td><td>'+(!x.verified&&(evidence?.verified||evidence?.status==="VERIFIED")?button("Vérifier","verify-fact:"+x.evidence_id+":"+caseId+":"+x.fact_id):"")+( !(evidence?.verified||evidence?.status==="VERIFIED")?'<small>Vérifier d’abord la preuve</small>':"") +'</td></tr>'}).join("")+'</tbody></table></div>'}function contradictionsMarkup(rows){if(!rows.length)return '<p class="muted">Aucune contradiction enregistrée. Une analyse peut être lancée par un administrateur.</p>';return '<div class="table"><table><thead><tr><th>Description</th><th>Éléments</th><th>Statut</th></tr></thead><tbody>'+rows.map(x=>'<tr><td>'+esc(x.description)+'</td><td>'+esc((x.evidence_ids||[]).join(", "))+'</td><td>'+esc(x.disposition?.status||"À examiner")+'</td></tr>').join("")+'</tbody></table></div>'}function renderDetail(root,kind,id,title,d){let body="",actions="";
if(kind==="reviews"){const r=d.review||{};body='<div class="detail-grid">'+field("Identifiant",r.review_id)+field("Auteur",r.author_display_name)+field("Note",r.rating+"/5")+field("Publié le",fmt(r.published_at))+field("Source",r.source)+field("Langue",r.language)+'</div><h3>Texte de l’avis</h3><p>'+esc(r.text)+'</p><h3>Réclamations / affirmations détectées</h3>'+jsonBlock(d.claims||[])+ '<h3>Signaux de politique</h3>'+jsonBlock(d.policy_signals||[]);if(["CLIENT","OWNER","ADMIN","ANALYST"].includes(S.role))actions+=button("Créer un dossier","create-case:"+id,"btn primary")}
else if(kind==="cases"){const c=d.detail?.case||d.detail?.case||{},w=d.workspace?.workspace||{};body='<div class="detail-grid">'+field("Identifiant",c.case_id||id)+field("Statut",c.status)+field("Avis associé",c.review_id)+field("Assigné à",c.assigned_to)+field("Créé le",fmt(c.created_at))+field("SLA",d.sla?.sla?.status||d.sla?.status)+'</div><h3>Avis associé</h3><p>'+esc(d.detail?.review?.text||w.review?.text)+'</p><h3>Signaux et affirmations</h3>'+jsonBlock({claims:d.detail?.claims,policy_signals:d.detail?.policy_signals})+'<h3>Checklist / préparation</h3>'+jsonBlock(d.checklist||d.checklist_error)+'<h3>Matrice des preuves</h3>'+jsonBlock(d.matrix?.matrix||d.matrix_error)+'<h3>Preuves</h3>'+jsonBlock(w.evidence||[])+'<h3>Faits extraits à vérifier</h3>'+factsMarkup(d.workspace?.fact_suggestions||[],w.evidence||[],id)+'<h3>Contradictions détectées</h3>'+contradictionsMarkup(d.contradictions?.contradictions||[])+'<h3>Historique</h3>'+jsonBlock(d.history?.items||d.history_error)+'<h3>Décision et approbations</h3>'+jsonBlock({decision:d.workspace?.decision,approvals:d.workspace?.approvals,snapshot:d.workspace?.snapshot});
if(can("operator")){actions+=button("Ajouter une preuve","upload-evidence:"+id,"btn primary");actions+=button(c.assigned_to?"Libérer l’affectation":"Prendre en charge","claim-case:"+id);actions+=button("Vérifier checklist","checklist:"+id);}
if(can("manager")){actions+=button("Extraire les faits","extract-facts:"+id);actions+=button("Analyser les contradictions","analyze-contradictions:"+id);actions+=button("Créer une décision","decision:"+id);if(c.decision_id)actions+=button("Geler la décision","freeze:"+id);actions+=button("Mettre en pause SLA","pause-sla:"+id);actions+=button("Reprendre SLA","resume-sla:"+id);actions+=button("Approuver","approve:"+id);actions+=button("Préparer la soumission","submit:"+id)}}
else if(kind==="team"){const m=d||{};body='<div class="detail-grid">'+field("Identifiant",m.user_id)+field("Email",m.email)+field("Rôle",m.role)+'</div><p>Un changement de rôle invalide les sessions existantes du membre.</p>';if(can("manager")&&m.user_id!==undefined)actions+=button("Modifier le rôle","edit-role:"+m.user_id,"btn primary")}
else if(kind==="notifications"){const n=d||{};body='<div class="detail-grid">'+field("Sujet",n.subject)+field("Canal",n.channel)+field("Statut",n.status)+field("Créée le",fmt(n.created_at))+field("Destinataire",n.target)+'</div><h3>Contenu</h3><p>'+esc(n.body)+'</p>';if(can("manager")&&!["SENT","CANCELLED","DELIVERED"].includes(n.status)){actions+=button("Envoyer maintenant","deliver-notification:"+id,"btn primary");actions+=button("Annuler","cancel-notification:"+id)}}
else if(kind==="escalations"){const x=d||{};body='<div class="detail-grid">'+field("Dossier",x.case_id)+field("Niveau",x.level)+field("État",x.status)+field("Assigné",x.assigned_to)+field("Priorité SLA",x.sla?.priority)+field("Temps restant (s)",x.sla?.remaining_seconds)+'</div>';if(can("operator")&&x.status!=="RESOLVED"){actions+=button("Prendre en compte","ack-escalation:"+x.case_id+":"+x.level);actions+=button("Résoudre","resolve-escalation:"+x.case_id+":"+x.level)}}
else if(kind==="evidence"){const e=d.evidence||{};body='<div class="detail-grid">'+field("Fichier",e.filename)+field("Dossier",e.case_id)+field("Type",e.content_type)+field("Taille",e.size_bytes+" octets")+field("SHA-256",e.sha256)+field("État",e.status)+'</div><p>La vérification contrôle l’intégrité du fichier côté serveur.</p>';if(e.download_url)body+='<p><a href="'+esc(e.download_url)+'" target="_blank" rel="noopener">Télécharger la preuve</a></p>';if(can("operator")&&!e.verified)actions+=button("Vérifier l’intégrité","verify-evidence:"+id,"btn primary")}
else body=jsonBlock(d);
root.innerHTML='<div class="overlay"><section class="card drawer"><button class="btn close" data-action="close">×</button><h2>'+esc(title)+'</h2><p class="muted">Données et opérations issues du backend Review Defense.</p><div class="actions" style="flex-wrap:wrap;margin:14px 0">'+actions+'</div>'+body+'</section></div>'}
function modal(title,form){const root=document.getElementById("modal-root");root.innerHTML='<div class="overlay"><section class="card drawer"><button class="btn close" data-action="close">×</button><h2>'+esc(title)+'</h2>'+form+'</section></div>'}
async function onAction(e){const b=e.target.closest("[data-action]");if(!b)return;const action=b.dataset.action;if(action==="close"){document.getElementById("modal-root").innerHTML="";return}
const [op,id]=action.split(":");try{
if(op==="invite-member"){modal("Inviter un membre",'<form id="invite-form"><div class="field"><label>Adresse email</label><input name="email" type="email" required></div><div class="field"><label>Rôle</label><select name="role"><option value="CLIENT">Client</option><option value="ANALYST">Analyste</option><option value="VIEWER">Lecture seule</option><option value="ADMIN">Administrateur</option></select></div><button class="btn primary">Créer l’invitation</button><p class="notice">Le backend crée un jeton à usage unique. Cette action n’envoie pas d’email.</p></form>');document.getElementById("invite-form").onsubmit=async ev=>{ev.preventDefault();const result=await post("/v1/organization/invitations",Object.fromEntries(new FormData(ev.currentTarget)));S.lastInvitationToken=result.invitation_token;modal("Invitation créée",'<p>Copiez et transmettez ce jeton à la personne invitée. Il ne sera affiché qu’une fois.</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere">'+esc(result.invitation_token)+'</pre><p class="muted">Expiration : '+esc(fmt(result.expires_at))+'</p><button class="btn primary" data-action="copy-token">Copier le jeton</button>');S.cache.team=arr(await api("/v1/organization/members"));};return}
if(op==="copy-token"){await navigator.clipboard.writeText(S.lastInvitationToken||"");b.textContent="Copié";return}
if(op==="edit-role"){const member=(S.cache.team||[]).find(x=>x.user_id===id);if(!member)return;modal("Modifier le rôle",'<form id="role-form"><div class="field"><label>Membre</label><input value="'+esc(member.email)+'" disabled></div><div class="field"><label>Nouveau rôle</label><select name="role"><option value="CLIENT">Client</option><option value="ANALYST">Analyste</option><option value="VIEWER">Lecture seule</option><option value="ADMIN">Administrateur</option><option value="OWNER">Propriétaire</option></select></div><button class="btn primary">Enregistrer</button></form>');document.querySelector("#role-form [name=role]").value=member.role;document.getElementById("role-form").onsubmit=async ev=>{ev.preventDefault();await post("/v1/organization/members/"+encodeURIComponent(id)+"/role",Object.fromEntries(new FormData(ev.currentTarget)));S.cache.team=arr(await api("/v1/organization/members"));await load("team");document.getElementById("modal-root").innerHTML="";};return}
if(op==="ack-escalation"||op==="resolve-escalation"){const parts=action.split(":");const caseId=parts[1],level=parts[2];await post("/v1/escalations/"+encodeURIComponent(caseId)+"/"+(op==="ack-escalation"?"acknowledge":"resolve"),{level});S.cache.escalations=arr(await api("/v1/escalations"));return openDetail("escalations",caseId)}
if(op==="deliver-notification"||op==="cancel-notification"){await post("/v1/notifications/"+encodeURIComponent(id)+"/"+(op==="deliver-notification"?"deliver":"cancel"));S.cache.notifications=arr(await api("/v1/notifications"));return openDetail("notifications",id)}
if(op==="create-case"){await post("/v1/cases",{review_id:id});document.getElementById("modal-root").innerHTML="";S.view="cases";show();return}
if(op==="verify-evidence"){await post("/v1/evidence/"+encodeURIComponent(id)+"/verify");return openDetail("evidence",id)}
if(op==="extract-facts"){await post("/v1/cases/"+id+"/extract-facts",{});return openDetail("cases",id)}
if(op==="analyze-contradictions"){await post("/v1/cases/"+id+"/contradictions",{});return openDetail("cases",id)}
if(op==="verify-fact"){const parts=action.split(":");const evidenceId=parts[1],caseId=parts[2],factId=parts[3];await post("/v1/evidence/"+encodeURIComponent(evidenceId)+"/facts/verify",{fact_ids:[factId]});return openDetail("cases",caseId)}
if(op==="disposition"){const parts=action.split(":");const caseId=parts[1],contradictionId=parts[2];modal("Qualifier la contradiction",'<form id="disposition-form"><div class="field"><label>Qualification</label><select name="status" required><option value="CONFIRMED">Confirmée</option><option value="DISMISSED">Écartée</option><option value="NEEDS_REVIEW">À approfondir</option></select></div><div class="field"><label>Justification</label><textarea name="rationale" required rows="4"></textarea></div><button class="btn primary">Enregistrer</button></form>');document.getElementById("disposition-form").onsubmit=async ev=>{ev.preventDefault();await post("/v1/cases/"+caseId+"/contradictions/"+contradictionId+"/disposition",Object.fromEntries(new FormData(ev.currentTarget)));await openDetail("cases",caseId)};return}
if(op==="claim-case"){const row=(S.cache.queue||[]).find(x=>x.case_id===id);await post("/v1/review-queue/"+encodeURIComponent(id)+(row?.assigned_to?"/unclaim":"/claim"));return openDetail("cases",id)}
if(op==="upload-evidence"){modal("Ajouter une preuve",'<form id="evidence-form"><div class="field"><label>Fichier</label><input type="file" name="file" required></div><button class="btn primary">Envoyer la preuve</button><p class="notice">Le fichier est transmis au serveur via le endpoint sécurisé de dépôt.</p></form>');document.getElementById("evidence-form").onsubmit=async ev=>{ev.preventDefault();const file=ev.currentTarget.elements.file.files[0];const b64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]);reader.onerror=reject;reader.readAsDataURL(file)});await post("/v1/evidence",{case_id:id,filename:file.name,content_type:file.type||"application/octet-stream",content_base64:b64});await openDetail("cases",id)};return}
if(op==="decision"){modal("Créer une décision",'<form id="decision-form"><div class="field"><label>Type</label><select name="kind"><option value="HUMAN_REVIEW">Examen humain</option><option value="NO_ACTION">Aucune action</option></select></div><div class="field"><label>Motif obligatoire</label><textarea name="rationale" required rows="5"></textarea></div><button class="btn primary">Enregistrer la décision</button></form>');document.getElementById("decision-form").onsubmit=async ev=>{ev.preventDefault();await post("/v1/cases/"+id+"/decision",Object.fromEntries(new FormData(ev.currentTarget)));await openDetail("cases",id)};return}
if(op==="freeze"){if(!confirm("Geler la décision et créer son instantané ?"))return;await post("/v1/cases/"+id+"/freeze");return openDetail("cases",id)}
if(op==="approve"){if(!confirm("Confirmer l’approbation de la décision gelée ?"))return;await post("/v1/cases/"+id+"/approve");return openDetail("cases",id)}
if(op==="submit"){if(!confirm("Préparer la soumission ? Cette action sera enregistrée côté serveur."))return;await post("/v1/cases/"+id+"/submit",{});return openDetail("cases",id)}
if(op==="pause-sla"||op==="resume-sla"){if(op==="pause-sla"){modal("Mettre en pause le SLA",'<form id="sla-form"><div class="field"><label>Motif obligatoire</label><textarea name="reason" required maxlength="500" rows="4"></textarea></div><button class="btn primary">Confirmer la pause</button></form>');document.getElementById("sla-form").onsubmit=async ev=>{ev.preventDefault();await post("/v1/cases/"+id+"/pause-sla",Object.fromEntries(new FormData(ev.currentTarget)));await openDetail("cases",id)}}else{if(!confirm("Reprendre le SLA ?"))return;await post("/v1/cases/"+id+"/resume-sla");await openDetail("cases",id)}return}
if(op==="checklist"){const d=await api("/v1/cases/"+id+"/review-checklist");const rows=arr(d).length?arr(d):d.items||[];modal("Checklist du dossier",'<form id="checklist-form">'+rows.map(x=>'<label style="display:block;padding:10px;border-bottom:1px solid #eee"><input type="checkbox" data-code="'+esc(x.code)+'" '+(x.completed?"checked":"")+'> '+esc(x.label||x.code)+'</label>').join("")+'<button class="btn primary">Enregistrer les éléments cochés</button></form>');document.getElementById("checklist-form").onsubmit=async ev=>{ev.preventDefault();for(const input of ev.currentTarget.querySelectorAll("[data-code]"))await post("/v1/cases/"+id+"/review-checklist",{code:input.dataset.code,completed:input.checked});await openDetail("cases",id)};return}
}catch(err){modal("Action non effectuée",'<div class="notice">'+esc(err.message)+'</div>')}}
async function start(){if(!S.token)return login();try{const me=await api("/v1/me");S.role=me.role||S.role;localStorage.setItem("rd_role",S.role);if(adminPath()&&!can("manager")){location.replace("/client");return}if(!adminPath()&&can("manager")){location.replace("/admin");return}shell()}catch(e){localStorage.removeItem("rd_token");localStorage.removeItem("rd_role");S.token=null;login()}}
start();
})();