import{useEffect,useState}from"react";import{useNavigate}from"react-router-dom";import{api}from"@/services/api/client";import{useAuth}from"@/auth/AuthContext";
import { PageHeading } from "@/components/layout/PageHeading";
import { FeedbackMessage } from "@/components/common/FeedbackMessage";
type Member={user_id:string;email:string;role:string};
type Invitation={invitation_id:string;email:string;role:string;expires_at?:string};
export function AdminPage(){
const[members,setMembers]=useState<Member[]>([]),[lastInvitation,setLastInvitation]=useState<Invitation|null>(null),[email,setEmail]=useState(""),[role,setRole]=useState("ANALYST"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
const{user,logout}=useAuth(),navigate=useNavigate(),isOwner=user?.role==="OWNER";
const load=()=>api.get<{items:Member[]}>("/v1/organization/members").then(x=>setMembers(x.items??[])).catch(e=>setError(e instanceof Error?e.message:"Administration indisponible"));
useEffect(()=>{void load()},[]);
const invite=async()=>{setError("");setBusy(true);try{const x=await api.post<Invitation>("/v1/organization/invitations",{email,role});setLastInvitation({invitation_id:x.invitation_id,email:x.email??email,role:x.role??role,expires_at:x.expires_at});setEmail("");await load()}catch(e){setError(e instanceof Error?e.message:"Invitation impossible")}finally{setBusy(false)}};
const change=async(id:string,nextRole:string)=>{setError("");try{await api.post("/v1/organization/members/"+id+"/role",{role:nextRole});await load()}catch(e){setError(e instanceof Error?e.message:"Modification impossible")}};
const revokeSessions=async()=>{setError("");setBusy(true);try{await api.post("/v1/auth/revoke-all");await logout().catch(()=>undefined);navigate("/login",{replace:true})}catch(e){setError(e instanceof Error?e.message:"Révocation impossible");setBusy(false)}};
return <section className="workspace"><PageHeading eyebrow="ADMINISTRATION" title="L’espace de contrôle." description="Membres, rôles, invitations et sessions de l’organisation." action={<button className="button button-dark" disabled={busy} onClick={()=>void revokeSessions()}>Révoquer mes sessions et me déconnecter</button>} />{error&&<FeedbackMessage className="form-error" role="alert">{error}</FeedbackMessage>}<div className="create-bar"><input type="email" placeholder="adresse@entreprise.fr" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option>ANALYST</option><option>CLIENT</option><option>VIEWER</option><option>ADMIN</option></select><button className="button button-secondary" disabled={busy||!email.trim()} onClick={()=>void invite()}>Inviter →</button></div>{lastInvitation&&<article className="panel"><span className="eyebrow">DERNIÈRE INVITATION CRÉÉE</span><h2>{lastInvitation.email}</h2><p>{lastInvitation.role} · expiration {lastInvitation.expires_at??"non communiquée"}</p><small>La route API actuelle permet de créer une invitation, mais ne fournit pas de consultation de la liste des invitations existantes.</small></article>}<div className="panel table-panel">{members.map(x=><div className="case-row" key={x.user_id}><div className="avatar">{(x.email?.[0]??"U").toUpperCase()}</div><div><b>{x.email}</b><p>{x.user_id}</p></div><select value={x.role} onChange={e=>void change(x.user_id,e.target.value)}>{(isOwner||x.role==="OWNER")&&<option>OWNER</option>}<option>ADMIN</option><option>ANALYST</option><option>CLIENT</option><option>VIEWER</option></select><span>↗</span></div>)}</div></section>;
}