import{useEffect,useState}from"react";import{Link}from"react-router-dom";import{api}from"@/services/api/client";
import { PageHeading } from "@/components/layout/PageHeading";
import { FeedbackMessage } from "@/components/common/FeedbackMessage";
export function AnalysisPage(){const[q,setQ]=useState<any[]>([]),[w,setW]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{Promise.all([api.get<any>("/v1/review-queue"),api.get<any>("/v1/review-queue/workload")]).then(([a,b])=>{setQ(a.items??[]);setW(b)}).catch(e=>setError(e instanceof Error?e.message:"Impossible de charger la file d’analyse.")).finally(()=>setLoading(false))},[]);
const count=(p:string)=>q.filter(x=>String(x.priority).toUpperCase()===p).length;
return <section className="workspace"><PageHeading as="header" className="module-heading" eyebrow="ANALYSE" title="La file de travail." description="Priorisez ce qui mérite une lecture humaine et gardez une vue claire de la charge." action={<Link className="module-refresh" to="/app/analysis">Actualiser</Link>} />{error&&<FeedbackMessage className="form-error" role="alert">{error}</FeedbackMessage>}
<div className="analysis-kpis"><div><span>TOTAL</span><strong>{loading?"—":q.length}</strong></div><div><span>CRITIQUES</span><strong>{loading?"—":count("CRITICAL")}</strong></div><div><span>ÉLEVÉS</span><strong>{loading?"—":count("HIGH")}</strong></div><div><span>CHARGE</span><strong>{loading?"—":(w?.items??[]).reduce((sum:any,row:any)=>sum+(Number(row.case_count)||0),0)}</strong></div></div>
<div className="module-table"><table><thead><tr><th>Dossier</th><th>Priorité</th><th>Score</th><th>SLA</th><th></th></tr></thead><tbody>{q.map(x=><tr key={x.case_id}><td><Link className="review-open" to={"/app/cases/"+x.case_id}>{x.case_id}</Link></td><td><span className={"priority-pill priority-"+String(x.priority??"low").toLowerCase()}>{x.priority??x.status}</span></td><td>{x.priority_score??"—"}</td><td>{x.sla?.status??"—"}</td><td><Link className="review-open" to={"/app/cases/"+x.case_id}>Ouvrir →</Link></td></tr>)}</tbody></table>{!loading&&!q.length&&<FeedbackMessage className="module-empty">Aucun élément dans la file.</FeedbackMessage>}{loading&&<FeedbackMessage className="module-empty">Chargement de la file…</FeedbackMessage>}</div></section>;}
