import{useEffect,useState}from"react";import{Link,useParams}from"react-router-dom";import{api}from"@/services/api/client";
import { PageHeading } from "@/components/layout/PageHeading";
type Evidence={evidence_id:string;filename:string;evidence_type:string;status:string};
type Workspace={state:string;priority:string;review:{author_display_name?:string|null;text?:string;rating?:number;source?:string};evidence:Evidence[];evidence_coverage?:number;claims?:{claim_id:string;text:string;claim_type:string;status:string}[];policies?:{code:string;status:string;justification?:string}[];contradictions?:{contradiction_id:string;description:string;requires_human_review:boolean}[]};
type WorkspaceResponse={workspace:Workspace;evidence_tasks:{task_id:string;evidence_requirement:string;priority:string;status:string}[];requires_human_review:boolean};
export function CaseDetailPage(){
const{id}=useParams(),[data,setData]=useState<WorkspaceResponse|null>(null),[error,setError]=useState("");
useEffect(()=>{let active=true;if(id)api.get<WorkspaceResponse>("/v1/cases/"+id+"/workspace").then(x=>{if(active)setData(x)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Impossible de charger le dossier")});return()=>{active=false}},[id]);
if(error)return <section className="workspace"><Link to="/app/cases" className="back-link">← Tous les dossiers</Link><div className="form-error" role="alert">{error}</div></section>;
if(!data)return <section className="workspace"><div className="empty">Chargement du dossier…</div></section>;
const w=data.workspace,review=w.review,evidence=w.evidence??[],tasks=data.evidence_tasks??[];
return <section className="workspace"><Link to="/app/cases" className="back-link">← Tous les dossiers</Link><PageHeading eyebrow="DOSSIER" title={id ?? "Dossier"} description="Workspace de décision et de preuves." action={<span className="status-pill">{w.state??"OPEN"}</span>} /><div className="content-grid"><article className="panel"><span className="eyebrow">AVIS</span><h2>{review.author_display_name??"Avis sélectionné"}</h2><blockquote>{review.text??"Aucun texte disponible."}</blockquote><div className="detail-meta"><span>Note</span><b>{review.rating??"—"}</b><span>Source</span><b>{review.source??"—"}</b><span>Priorité</span><b>{w.priority??"—"}</b></div></article><article className="panel"><span className="eyebrow">PREUVES</span><h2>Éléments du dossier</h2>{evidence.map(x=><div className="signal-row" key={x.evidence_id}><span className="priority-dot"/><span>{x.filename} · {x.status}</span></div>)}{!evidence.length&&<div className="empty">Aucune preuve enregistrée.</div>}<div className="panel-head"><h3>Éléments à réunir</h3></div>{tasks.map(x=><div className="signal-row" key={x.task_id}><span className="priority-dot"/><span>{x.evidence_requirement} · {x.status}</span></div>)}{!tasks.length&&<div className="empty">Aucun élément manquant identifié.</div>}<p>Couverture des preuves : {Math.round((w.evidence_coverage??0)*100)}%</p></article></div></section>;
}