import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { ApiError,api } from "@/services/api/client";
import type { Case,Review } from "@/types/api";
export function CasesPage(){const [items,setItems]=useState<Case[]>([]),[reviews,setReviews]=useState<Review[]>([]),[reviewId,setReviewId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState<ApiError|null>(null),[creating,setCreating]=useState(false);
const load=async()=>{setLoading(true);try{const [c,r]=await Promise.all([api.get<{items:Case[]}>("/v1/cases"),api.get<{items:Review[]}>("/v1/reviews")]);setItems(c.items??[]);setReviews(r.items??[])}catch(e){setError(e instanceof ApiError?e:new ApiError("Impossible de charger les dossiers.",0))}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
const create=async()=>{if(!reviewId)return;setCreating(true);setError(null);try{await api.post("/v1/cases",{review_id:reviewId});setReviewId("");await load()}catch(e){setError(e instanceof ApiError?e:new ApiError("Impossible de créer le dossier.",0))}finally{setCreating(false)}};
return <section className="module-page"><div className="module-heading"><div><span className="eyebrow">REVIEW DEFENSE · DOSSIERS</span><h1>Dossiers</h1><p>Suivez les dossiers ouverts à partir des avis et accédez à leur espace de travail.</p></div><Button variant="secondary" onClick={()=>void load()} disabled={loading}>Actualiser</Button></div>
<div className="module-create"><div><strong>Ouvrir un dossier</strong><span>Sélectionnez un avis existant.</span></div><select value={reviewId} onChange={e=>setReviewId(e.target.value)}><option value="">Choisir un avis…</option>{reviews.map(r=><option key={r.review_id} value={r.review_id}>{r.author_display_name||"Avis"} · {r.rating}/5 · {r.text.slice(0,55)}</option>)}</select><Button onClick={()=>void create()} disabled={!reviewId||creating}>{creating?"Création…":"Créer le dossier"}</Button></div>
{error&&<div className="dashboard-error" role="alert"><strong>{error.message}</strong></div>}<div className="module-table"><table><thead><tr><th>Dossier</th><th>Statut</th><th>Priorité</th><th>Créé</th><th/></tr></thead><tbody>{loading?<tr><td colSpan={5}>Chargement…</td></tr>:items.length?items.map(c=><tr key={c.case_id}><td><strong>{c.case_id}</strong></td><td><span className="status-pill">{c.status}</span></td><td>{c.priority||"NORMAL"}</td><td>{c.created_at?new Date(c.created_at).toLocaleDateString("fr-FR"):"—"}</td><td><Link className="review-open" to={"/app/cases/"+c.case_id}>Ouvrir</Link></td></tr>):<tr><td colSpan={5}><div className="module-empty">Aucun dossier.</div></td></tr>}</tbody></table></div></section>}