import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {api} from "@/services/api/client";
import { SectionHeading } from "@/components/layout/SectionHeading";
type Review={review_id:string;rating:number;text:string;author_display_name?:string|null;published_at?:string|null};
type Case={case_id:string;status:string;priority?:string};
type Queue={case_id:string;priority?:string;priority_score?:number;status:string};
const formatDate=(value?:string|null)=>value?new Date(value).toLocaleDateString("fr-FR",{day:"2-digit",month:"short"}):"—";
export function DashboardPage(){const[reviews,setReviews]=useState<Review[]>([]),[cases,setCases]=useState<Case[]>([]),[queue,setQueue]=useState<Queue[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{Promise.all([api.get<{items:Review[]}>("/v1/reviews"),api.get<{items:Case[]}>("/v1/cases"),api.get<{items:Queue[]}>("/v1/review-queue")]).then(([a,b,c])=>{setReviews(a.items??[]);setCases(b.items??[]);setQueue(c.items??[])}).catch(e=>setError(e instanceof Error?e.message:"Impossible de charger votre activité.")).finally(()=>setLoading(false))},[]);
const average=reviews.length?(reviews.reduce((sum,x)=>sum+x.rating,0)/reviews.length).toFixed(1):"—";const critical=queue.filter(x=>String(x.priority).toUpperCase()==="CRITICAL").length;
return <section className="dashboard-page"><header className="dashboard-hero"><div className="dashboard-hero-copy"><span className="eyebrow">VUE D’ENSEMBLE</span><h1>Votre activité,<br/><em>en un coup d’œil.</em></h1><p>Les signaux importants sont regroupés ici pour que votre équipe sache quoi regarder ensuite.</p></div><div className="dashboard-hero-actions"><Link className="button button-primary" to="/app/reviews">Voir les avis →</Link><Link className="button button-secondary" to="/app/cases">Ouvrir les dossiers</Link></div></header>
{error&&<div className="dashboard-error" role="alert"><div><strong>Le tableau de bord n’a pas pu être chargé.</strong><span>{error}</span></div><Link className="button button-secondary" to="/app/dashboard">Réessayer</Link></div>}
<div className="dashboard-metrics"><article><span>Avis suivis</span><strong>{loading?"—":reviews.length}</strong><small>dans votre espace</small></article><article className="dashboard-metric-focus"><span>Note moyenne</span><strong>{loading?"—":average}</strong><small>sur les avis chargés</small></article><article><span>Dossiers</span><strong>{loading?"—":cases.length}</strong><small>créés dans l’espace</small></article><article><span>À examiner</span><strong>{loading?"—":queue.length}</strong><small>{critical?critical+" critique"+(critical>1?"s":""):"aucun critique"}</small></article></div>
<div className="dashboard-main-grid"><article className="dashboard-surface"><SectionHeading eyebrow="RÉCENTS" title="Derniers avis" action={<Link to="/app/reviews" className="review-open">Tout voir →</Link>} />{reviews.slice(0,6).map(x=><Link className="dashboard-review-row" key={x.review_id} to={"/app/reviews/"+x.review_id}><span className="dashboard-rating">{x.rating}<small>/5</small></span><div className="dashboard-review-content"><strong>{x.author_display_name||"Client"}</strong><span>{x.text.length>120?x.text.slice(0,120)+"…":x.text}</span></div><time>{formatDate(x.published_at)}</time><b>→</b></Link>)}{!reviews.length&&!loading&&<div className="dashboard-empty"><strong>Aucun avis à afficher.</strong><span>Les nouveaux avis apparaîtront ici.</span></div>}</article>
<article className="dashboard-surface"><SectionHeading eyebrow="PRIORITÉ" title="À examiner" action={<Link to="/app/analysis" className="review-open">Analyse →</Link>} />{queue.slice(0,6).map(x=><Link className="dashboard-queue-row" key={x.case_id} to={"/app/cases/"+x.case_id}><i>!</i><div><strong>Dossier {x.case_id.slice(0,8)}</strong><span>Score {x.priority_score??"—"} · {x.status}</span></div><span className={"dashboard-priority dashboard-priority-"+String(x.priority??"low").toLowerCase()}>{x.priority??"standard"}</span></Link>)}{!queue.length&&!loading&&<div className="dashboard-empty"><strong>La file est vide.</strong><span>Aucune intervention prioritaire actuellement.</span></div>}</article></div>
<div className="dashboard-lower-grid"><article className="dashboard-surface"><SectionHeading eyebrow="RÉPARTITION" title="État des dossiers" /><div className="dashboard-status-list">{["OPEN","IN_PROGRESS","PENDING","CLOSED"].map(status=><div key={status}><span>{status.replace("_"," ")}</span><strong>{cases.filter(x=>String(x.status).toUpperCase()===status).length}</strong></div>)}</div></article>
<article className="dashboard-surface"><SectionHeading eyebrow="PROCHAINE ÉTAPE" title="Continuer le travail" /><div className="dashboard-next-content"><i>→</i><div><strong>{queue[0]?"Dossier "+queue[0].case_id.slice(0,8):"Aucun dossier prioritaire"}</strong><span>{queue[0]?"Revoir les éléments et ouvrir le dossier.":"Votre espace est à jour."}</span></div>{queue[0]&&<Link to={"/app/cases/"+queue[0].case_id}>Ouvrir →</Link>}</div></article></div></section>;}
