import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "@/services/api/client";
import { authToken } from "@/auth/AuthContext";
import { PublicHeader as Header } from "@/components/layout/PublicHeader";
import { PublicFooter as Footer } from "@/components/layout/PublicFooter";
import "@/styles/public.css";

declare global { interface Window { paypal?: { Buttons: (options: any) => { render: (selector: string) => Promise<void> | void }; HostedButtons?: (options: any) => { render: (selector: string) => Promise<void> | void } } } }

export function PricingPage() {
  const [catalog, setCatalog] = useState<any[]>([]);
  const [error, setError] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const groups = [
    { key:"subscription", eyebrow:"MONITORING", title:"Abonnements", description:"Un abonnement mensuel pour organiser votre activité et suivre vos dossiers dans le temps.", kinds:["subscription"] },
    { key:"audit", eyebrow:"AUDIT", title:"Audits de réputation", description:"Une prestation ponctuelle pour analyser un volume défini d’avis et structurer votre travail.", kinds:["audit"] },
    { key:"defense", eyebrow:"DÉFENSE / SUPPRESSION", title:"Défense d’un avis", description:"Un avis précis peut être traité par étapes, de l’analyse initiale aux niveaux de traitement disponibles.", kinds:["defense_step","defense_package"] },
  ] as const;
  useEffect(() => { api.get<any>("/v1/billing/catalog").then(d=>setCatalog(d.items??[])).catch(e=>setError(e instanceof Error?e.message:"Le catalogue tarifaire est temporairement indisponible.")); }, []);
  const loadPayPal = async (clientId:string, components:string, extra="") => {
    const old=document.querySelector<HTMLScriptElement>("script[data-rd-paypal]");if(old)old.remove();
    await new Promise<void>((resolve,reject)=>{const s=document.createElement("script");s.src="https://www.paypal.com/sdk/js?client-id="+encodeURIComponent(clientId)+"&components="+components+"&currency=EUR&locale=fr_FR"+extra;s.async=true;s.dataset.rdPaypal="1";s.onload=()=>resolve();s.onerror=()=>reject(new Error("Impossible de charger PayPal."));document.head.appendChild(s)});
    if(!window.paypal)throw new Error("Le service de paiement est momentanément indisponible.");
  };
  const payOneTime=async(offer:any)=>{setError("");setMessage("");setSelected(offer.offer_id);try{if(!offer.paypal_hosted_button_id)throw new Error("Le paiement en ligne n’est pas disponible pour cette offre pour le moment.");await loadPayPal("BAAftx79q4rSHY7vc2aYy_hgx3KB6GB15k__TBghUQyd1_ixXSqv71UHw1RXZvkR4cli25WsSirUKWt7zs","hosted-buttons");const id="paypal-"+offer.offer_id,node=document.getElementById(id);if(!node)throw new Error("Conteneur PayPal introuvable.");node.innerHTML="";const pp=window.paypal;if(!pp.HostedButtons)throw new Error("Les boutons PayPal hébergés sont indisponibles.");pp.HostedButtons({hostedButtonId:offer.paypal_hosted_button_id}).render("#"+id)}catch(e){setError(e instanceof Error?e.message:"Le paiement n’a pas pu être préparé.");setSelected(null)}};
  const subscribe=async(offer:any)=>{setError("");setMessage("");setSelected(offer.offer_id);const token=authToken();if(!token){setSelected(null);window.location.href="/register?next=/tarifs";return}try{const cfg=await api.get<any>("/v1/paypal/config");if(!cfg.configured||!cfg.client_id)throw new Error("Le paiement par abonnement n’est pas disponible pour le moment.");const plan=await api.get<any>("/v1/paypal/subscription/config?offer_id="+encodeURIComponent(offer.offer_id));await loadPayPal(cfg.client_id,"buttons","&vault=true&intent=subscription");const id="paypal-"+offer.offer_id,node=document.getElementById(id);if(!node)throw new Error("Conteneur PayPal introuvable.");node.innerHTML="";window.paypal?.Buttons({style:{layout:"vertical",label:"subscribe"},createSubscription:(_d:any,a:any)=>a.subscription.create({plan_id:plan.plan_id}),onApprove:async(data:any)=>{await api.post("/v1/paypal/subscription/confirm",{subscription_id:data.subscriptionID,offer_id:offer.offer_id},{headers:{Authorization:"Bearer "+token}});setMessage("Abonnement confirmé. Votre espace sera synchronisé avec PayPal.");setSelected(null)},onCancel:()=>setSelected(null),onError:(e:any)=>setError(e?.message??"Erreur de paiement PayPal.")}).render("#"+id)}catch(e){setError(e instanceof Error?e.message:"PayPal indisponible.");setSelected(null)}};
  return <div className="rd-public rd-pricing-page"><Header/><main>
    <section className="rd-public-hero"><div><span className="rd-public-eyebrow">TARIFS</span><h1>Choisissez le format qui correspond <em>à votre besoin.</em></h1></div><div className="rd-public-hero-copy"><p>Abonnement de suivi, audit ponctuel ou traitement d’un avis précis. Commencez par le format qui correspond à votre usage actuel.</p></div></section>
    {error&&<div className="rd-pricing-alert" role="alert">{error}</div>}{message&&<div className="rd-pricing-success" role="status">{message}</div>}
    <section className="rd-billing-categories">{groups.map(group=>{const offers=catalog.filter(o=>(group.kinds as readonly string[]).includes(o.kind));return <section className="rd-billing-category" key={group.key}><div className="rd-billing-category-head"><div><span className="rd-public-eyebrow">{group.eyebrow}</span><h2>{group.title}</h2><p>{group.description}</p></div><span>{offers.length} offres</span></div><div className="rd-billing-grid">{offers.map(offer=>{const active=selected===offer.offer_id,isQuote=offer.amount===null,configured=Boolean(offer.paypal_hosted_button_id||offer.paypal_plan_id),price=isQuote?"Sur devis":Number(offer.amount).toLocaleString("fr-FR",{minimumFractionDigits:0,maximumFractionDigits:2})+" €"+(offer.recurring==="true"?" / mois":"");return <article className={"rd-billing-card"+(offer.offer_id==="monitoring_professional"||offer.offer_id==="defense_plus"?" featured":"")} key={offer.offer_id}><span className="rd-plan-label">{offer.kind==="subscription"?"ABONNEMENT":offer.kind==="audit"?"AUDIT":"DÉFENSE"}</span><h3>{offer.name_fr}</h3><strong>{price}</strong><p>{offer.kind==="audit"?"Prestation ponctuelle d’analyse structurée d’un volume défini d’avis.":offer.kind==="subscription"?"Abonnement mensuel pour organiser le suivi de votre activité.":"Étape ou niveau de traitement disponible pour un avis précis."}</p>{isQuote?<Link to="/register" className="rd-billing-button">Échanger sur mon besoin →</Link>:!configured?<button type="button" className="rd-billing-button disabled" disabled>Paiement en ligne indisponible</button>:active?<div id={"paypal-"+offer.offer_id} className="rd-paypal-hosted"/>:<button type="button" className="rd-billing-button" onClick={()=>offer.kind==="subscription"?void subscribe(offer):void payOneTime(offer)}>{offer.kind==="subscription"?"Souscrire →":"Payer en ligne →"}</button>}</article>})}</div></section>})}</section>
    <section className="rd-pricing-next"><span className="rd-public-eyebrow">BESOIN D’UN POINT DE DÉPART ?</span><h2>Vous pouvez commencer petit et élargir ensuite.</h2><div><Link className="rd-public-cta" to="/register">Créer mon espace →</Link><Link className="rd-public-secondary" to="/produit">Revoir le produit</Link></div></section>
  </main><Footer/></div>;
}