import { useState } from "react";
import { Link } from "react-router-dom";
import { PublicHeader as Header } from "@/components/layout/PublicHeader";
import { PublicFooter as Footer } from "@/components/layout/PublicFooter";
import "@/styles/public-pages-distinct.css";

const modes=[
 {n:"01",label:"Analyser",title:"Comprendre ce qui mérite un examen",text:"Le contenu reçu, le contexte disponible et les points à vérifier sont réunis au même endroit.",items:["Contenu reçu","Contexte disponible","Points à vérifier"]},
 {n:"02",label:"Documenter",title:"Construire un dossier exploitable",text:"Captures, documents, échanges et sources restent rattachés à la situation qu’ils éclairent.",items:["Sources rattachées","Pièces retrouvables","Contexte conservé"]},
 {n:"03",label:"Suivre",title:"Voir ce qui reste à faire",text:"Chaque dossier garde son état, son historique et la prochaine étape attendue.",items:["État du dossier","Historique","Prochaine étape"]},
 {n:"04",label:"Valider",title:"Garder la décision humaine",text:"Le logiciel peut préparer une action ; une personne habilitée garde la décision avant les étapes sensibles.",items:["Action proposée","Validation explicite","Trace de décision"]}
];

export function ProductPage(){
 const [active,setActive]=useState(0); const m=modes[active];
 return <div className="rd-product-page"><Header/><main>
  <section className="rd-product-hero"><div><span>LE PRODUIT</span><h1>Un poste de travail pour les avis qui demandent <em>du contexte.</em></h1><p>Review Defense transforme une situation dispersée en dossier lisible : ce qui est reçu, disponible, manquant et en attente de décision.</p><div className="rd-product-actions"><Link to="/register">Créer mon espace →</Link><Link to="/fonctionnement">Voir le parcours</Link></div></div><aside><strong>01</strong><b>ESPACE DE TRAVAIL</b><small>analyse · preuves · suivi · validation</small></aside></section>
  <section className="rd-product-tour"><nav>{modes.map((x,i)=><button key={x.n} className={i===active?"active":""} onClick={()=>setActive(i)}><span>{x.n}</span>{x.label}<b>→</b></button>)}</nav><div className="rd-product-tour-main"><div><small>{m.n} / 04</small><h2>{m.title}</h2><p>{m.text}</p><ul>{m.items.map(x=><li key={x}>✓ {x}</li>)}</ul></div><div className="rd-ui-preview"><div className="rd-ui-top"><b>Review Defense</b><span>Espace entreprise</span></div><div className="rd-ui-body"><aside><strong>RD</strong><span>Tableau</span><span className="on">{m.label}</span><span>Dossiers</span><span>Preuves</span><span>Suivi</span></aside><article><small>ESPACE DE TRAVAIL</small><h3>{m.title}</h3><div className="rd-ui-lines"><i/><i/><i/><i/></div><div className="rd-ui-footer"><b>{m.n}</b><span>validation requise</span></div></article></div></div></div></section>
  <section className="rd-product-capabilities"><span>CE QUE LE PRODUIT CENTRALISE</span><h2>Une situation.<br/><em>Un dossier de référence.</em></h2><div>{["Avis & contexte","Preuves & sources","Étapes & historique","Validation & responsabilité"].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>{["Le contenu reçu et les informations disponibles restent au point de départ.","Les éléments utiles restent attachés à la situation.","Le traitement conserve une chronologie lisible.","Les actions sensibles restent soumises à une validation."][i]}</p></article>)}</div></section>
  <section className="rd-product-proof"><div><span>LE RÉSULTAT</span><h2>Moins de dispersion.<br/><em>Plus de contexte.</em></h2></div><div><p>Le produit organise le travail nécessaire pour que la personne qui décide dispose des bons éléments au bon moment.</p><Link to="/tarifs">Voir le fonctionnement →</Link></div></section>
 </main><Footer/></div>;
}

const steps=[["01","Recevoir","Le signal devient le point de départ du dossier.","Entrée"],["02","Qualifier","Le contenu est distingué entre établi, disponible et à vérifier.","Lecture"],["03","Réunir","Les captures, documents et sources utiles rejoignent le dossier.","Preuves"],["04","Préparer","Les informations sont ordonnées pour rendre la suite compréhensible.","Préparation"],["05","Valider","Une personne habilitée décide de l’action à retenir.","Décision"],["06","Suivre","Le dossier reste exploitable après l’action.","Continuité"]];
export function MethodPage(){return <div className="rd-method-page"><Header/><main>
 <section className="rd-method-hero"><span>FONCTIONNEMENT</span><h1>Six étapes.<br/><em>Un même fil.</em></h1><p>Chaque étape produit le contexte utile à la suivante, sans transformer l’automatisation en décision.</p></section>
 <section className="rd-process"><div className="rd-process-rail"><span>DU SIGNAL</span><i/><span>AU SUIVI</span></div><div className="rd-process-list">{steps.map(([n,t,d,l],i)=><article className={i===4?"decision":""} key={n}><b>{n}</b><div><small>{l}</small><h2>{t}</h2><p>{d}</p></div><span>{i===4?"VALIDATION HUMAINE":"→"}</span></article>)}</div></section>
 <section className="rd-method-split"><div><span>LA LOGIQUE</span><h2>Chaque étape laisse<br/><em>quelque chose derrière elle.</em></h2></div><div className="rd-method-logic">{[["Reçu","Ce qui est entré dans le dossier."],["Vérifié","Ce qui a été examiné ou complété."],["Préparé","Ce qui est prêt pour la prochaine intervention."],["Décidé","Ce qui a été validé par une personne habilitée."]].map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div></section>
 <section className="rd-method-cta"><span>ÉTAPE SUIVANTE</span><h2>Voyez maintenant ce qui reste sous votre contrôle.</h2><Link to="/securite">Voir les contrôles →</Link></section>
 </main><Footer/></div>}

const controls=[["01","Accès","Utilisateurs et organisation"],["02","Permissions","Rôles et droits disponibles"],["03","Historique","Chronologie des événements importants"],["04","Preuves","Éléments liés à leur contexte"],["05","Validation","Décision conservée par une personne habilitée"],["06","Limites","Pas de promesse de certification ou de conseil juridique"]];
export function SecurityPage(){const faqs=[["Le logiciel décide-t-il à ma place ?","Non. Il prépare et organise le travail ; la décision sensible reste à la personne habilitée."],["Cette page est-elle une certification ?","Non. Elle présente des principes de contrôle du produit, pas une certification."],["Les permissions sont-elles identiques partout ?","Non. Elles dépendent de la configuration et du rôle dans l’organisation."]];return <div className="rd-security-page"><Header/><main>
 <section className="rd-security-hero"><div><span>SÉCURITÉ / CONTRÔLE</span><h1>Voir ce qui est contrôlé.<br/><em>Comprendre ce qui reste humain.</em></h1></div><div className="rd-security-note"><b>PRINCIPE</b><p>La sécurité se retrouve dans les accès, les permissions, la traçabilité, le contexte des preuves et les validations.</p></div></section>
 <section className="rd-security-dashboard"><header><span>CONTRÔLE DE L’ESPACE</span><b>6 axes</b></header><div>{controls.map(([n,t,d])=><article key={n}><small>{n}</small><div><h2>{t}</h2><p>{d}</p></div><b>ACTIF</b></article>)}</div></section>
 <section className="rd-security-model"><div><span>MODÈLE DE RESPONSABILITÉ</span><h2>Le logiciel prépare.<br/><em>L’humain tranche.</em></h2></div><div className="rd-security-flow"><div><small>LOGICIEL</small><b>Analyse</b><span>Structure le contenu</span></div><i>→</i><div><small>LOGICIEL</small><b>Prépare</b><span>Rassemble les éléments</span></div><i>→</i><div className="human"><small>HUMAIN</small><b>Valide</b><span>Décide de la suite</span></div></div></section>
 <section className="rd-security-faq"><div><span>QUESTIONS DE CONTRÔLE</span><h2>Les limites font partie<br/><em>du produit.</em></h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<b>+</b></summary><p>{a}</p></details>)}</div></section>
 <section className="rd-security-cta"><span>ÉTAPE SUIVANTE</span><h2>Comprendre les contrôles dans leur contexte.</h2><Link to="/tarifs">Voir les offres →</Link></section>
 </main><Footer/></div>}