import{useEffect,useMemo,useState}from"react";import{Link}from"react-router-dom";import{api}from"@/services/api/client";
import { PageHeading } from "@/components/layout/PageHeading";
type R={review_id:string;rating:number;text:string;author_display_name?:string|null;source?:string;published_at?:string|null};
export function ReviewsPage(){const[data,setData]=useState<R[]>([]),[query,setQuery]=useState(""),[rating,setRating]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");
useEffect(()=>{api.get<{items:R[]}>("/v1/reviews").then(x=>setData(x.items??[])).catch(e=>setError(e instanceof Error?e.message:"Impossible de charger les avis.")).finally(()=>setLoading(false))},[]);
const rows=useMemo(()=>data.filter(x=>(rating==="all"||String(x.rating)===rating)&&((x.text+" "+(x.author_display_name??"")).toLowerCase().includes(query.toLowerCase()))),[data,rating,query]);
return <section className="workspace"><PageHeading as="header" className="reviews-heading" eyebrow="AVIS" title="Votre bibliothèque d’avis." description="Recherchez, filtrez et ouvrez un avis pour lancer un dossier." action={<Link className="button button-secondary" to="/app/cases">Voir les dossiers →</Link>} />
<div className="reviews-toolbar"><label>Recherche<input aria-label="Rechercher un avis ou un auteur" placeholder="Rechercher un avis ou un auteur…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Note<select aria-label="Filtrer par note" value={rating} onChange={e=>setRating(e.target.value)}><option value="all">Toutes</option>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x} étoiles</option>)}</select></label><div className="reviews-summary"><span><strong>{loading?"—":rows.length}</strong> résultat{rows.length>1?"s":""}</span></div></div>
{error&&<div className="form-error" role="alert">{error}</div>}<div className="reviews-table-wrap"><table className="reviews-table"><thead><tr><th>Note</th><th>Avis</th><th>Source</th><th>Date</th><th></th></tr></thead><tbody>{rows.map(x=><tr key={x.review_id}><td><span className="review-rating">{x.rating}/5</span></td><td><div className="review-cell"><strong>{x.author_display_name||"Client"}</strong><span>{x.text}</span></div></td><td className="review-source">{x.source||"Google"}</td><td className="review-date">{x.published_at?new Date(x.published_at).toLocaleDateString("fr-FR"):"—"}</td><td><Link className="review-open" to={"/app/reviews/"+x.review_id}>Ouvrir →</Link></td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="reviews-table-empty"><strong>Aucun résultat.</strong><span>Modifiez votre recherche ou vos filtres.</span></div>}{loading&&<div className="reviews-table-empty">Chargement des avis…</div>}</div></section>;}
