import { useEffect,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { Button } from "@/components/ui/Button";
import { ApiError,api } from "@/services/api/client";
import type { Review } from "@/types/api";
type Claim={claim_id:string;text:string;claim_type?:string};type Signal={code:string;status:string;justification?:string};type Payload={review:Review;claims:Claim[];policy_signals:Signal[]};
const dateLabel=(value?:string|null)=>{if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium",timeStyle:"short"}).format(d)};
const label=(v?:string)=>v?v.replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase()):"—";
export function ReviewDetailPage(){const {reviewId}=useParams();const [data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<ApiError|null>(null);
 const load=async()=>{if(!reviewId)return;setLoading(true);setError(null);try{setData(await api.get<Payload>("/v1/reviews/"+encodeURIComponent(reviewId)))}catch(e){setError(e instanceof ApiError?e:new ApiError("Impossible de charger cet avis.",0))}finally{setLoading(false)}};useEffect(()=>{void load()},[reviewId]);
 if(loading)return <section className="review-detail-page"><Link className="back-link" to="/app/reviews">← Tous les avis</Link><div className="dashboard-empty">Chargement de l’avis…</div></section>;
 if(error||!data)return <section className="review-detail-page"><Link className="back-link" to="/app/reviews">← Tous les avis</Link><div className="dashboard-error" role="alert"><div><strong>Avis indisponible</strong><span>{error?.message??"Cet avis n’est plus accessible."}</span></div><Button variant="secondary" onClick={()=>void load()}>Réessayer</Button></div></section>;
 const {review,claims,policy_signals:signals}=data;return <section className="review-detail-page"><Link className="back-link" to="/app/reviews">← Tous les avis</Link><div className="review-detail-heading"><div><span className="eyebrow">REVIEW DEFENSE · FICHE AVIS</span><h1>{review.author_display_name||"Avis sans auteur"}</h1><p>{review.source} · publié le {dateLabel(review.published_at)}</p></div><div className="review-detail-rating">{review.rating}/5</div></div><div className="review-detail-grid"><article className="dashboard-card review-quote-card"><span className="dashboard-card-kicker">CONTENU</span><blockquote>{review.text}</blockquote>{review.review_url&&<a className="review-external" href={review.review_url} target="_blank" rel="noreferrer">Ouvrir la source ↗</a>}</article><article className="dashboard-card"><div className="dashboard-card-heading"><div><span className="dashboard-card-kicker">INFORMATIONS</span><h2>Métadonnées</h2></div></div><dl className="review-meta-list"><div><dt>Source</dt><dd>{review.source}</dd></div><div><dt>Langue</dt><dd>{review.language||"—"}</dd></div><div><dt>Lieu</dt><dd>{review.location_id||"—"}</dd></div><div><dt>Publié</dt><dd>{dateLabel(review.published_at)}</dd></div></dl></article><article className="dashboard-card"><div className="dashboard-card-heading"><div><span className="dashboard-card-kicker">ANALYSE</span><h2>Éléments identifiés</h2></div><span className="review-count">{claims.length}</span></div>{claims.length?<div className="review-detail-list">{claims.map(c=><div className="review-detail-item" key={c.claim_id}><strong>{c.text}</strong><span>{label(c.claim_type)}</span></div>)}</div>:<div className="dashboard-empty">Aucun élément identifié.</div>}</article><article className="dashboard-card"><div className="dashboard-card-heading"><div><span className="dashboard-card-kicker">SIGNAUX</span><h2>Policy signals</h2></div><span className="review-count">{signals.length}</span></div>{signals.length?<div className="review-detail-list">{signals.map(s=><div className="review-detail-item" key={s.code}><div><strong>{label(s.code)}</strong><span>{s.justification||"Aucune justification fournie."}</span></div><em className={"review-signal review-signal-"+s.status.toLowerCase()}>{label(s.status)}</em></div>)}</div>:<div className="dashboard-empty">Aucun signal retourné par l’API.</div>}</article></div></section>}